---
- name: include check_socket_container.yml
  include: check_socket_container.yml
  when:
    - containerized_deployment

- name: include check_socket_non_container.yml
  include: check_socket_non_container.yml
  when:
    - not containerized_deployment
